# Generated by Django 2.2.12 on 2024-12-28 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0003_auto_20241218_1844"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sujet",
            options={},
        ),
        migrations.RemoveField(
            model_name="sujet",
            name="cours",
        ),
        migrations.RemoveField(
            model_name="sujet",
            name="status",
        ),
        migrations.AlterField(
            model_name="sujet",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
