# Generated by Django 2.2.12 on 2024-12-28 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0012_matiere_instructor"),
        ("forum", "0004_auto_20241228_0802"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sujet",
            options={"verbose_name": "Sujet", "verbose_name_plural": "Sujets"},
        ),
        migrations.AddField(
            model_name="sujet",
            name="cours",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cours_forum",
                to="school.Cours",
            ),
        ),
        migrations.AddField(
            model_name="sujet",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="sujet",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_sujet",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
