# Generated by Django 2.2.12 on 2024-12-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instructor", "0007_forum_forumreponse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forum",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="forum",
            name="titre",
            field=models.CharField(max_length=200),
        ),
    ]
